apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      
      containers:
      - name: rabbitmq
        image: docker.io/bitnami/rabbitmq:3.8
        
        imagePullPolicy: Always
        ports:
        - name: rabbitmq
          containerPort: 4369
          containerPort: 5672
          containerPort: 25672
          containerPort: 15672
          protocol: TCP
        resources: {}
        
      restartPolicy: Always
      
      
      #volumes:
       # - name: configfiles-rabbitmq-data
        #  persistentVolumeClaim:
         #   claimName: configfiles-rabbitmq-data