apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: Cluste
  selector:
    app: rabbitmq 
  ports:
    - name: "4369"
      port: 4369
      targetPort: 4369
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "25672"
      port: 25672
      targetPort: 25672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
status:
  loadBalancer: {}
