# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 15672
#   selector:
#     app: rabbitmq
#   selector:
#     io.kompose.service: rabbitmq
# status:
#   loadBalancer: {}

apiVersion: v1
kind: Service
metadata:
  name: rabbit-lb
  labels:
    app: rabbitmq
spec:
  type: LoadBalancer
  ports:
  - port: 15672
  selector:
    app: rabbitmq