apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f rabbitmq.yaml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f rabbitmq.yaml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
        - image: docker.io/bitnami/rabbitmq:3.8
          name: rabbitmq
          ports:
            - containerPort: 4369
            - containerPort: 5672
            - containerPort: 25672
            - containerPort: 15672
          resources: {}
          volumeMounts:
            - mountPath: /bitnami
              name: otro-rabbitmq-data
      restartPolicy: Always
      volumes:
        - name: otro-rabbitmq-data
          persistentVolumeClaim:
            claimName: otro-rabbitmq-data
status: {}
